### ISSUE TITLE
TIFF validation problem

### ISSUE THREAD

**Issue by zsole** [KOST-CECO/KOST-Val#30]
Dear Clara,

We are converting images to tiff, and try to validate with KOST-val. In the JHOVE config byteoffset=true is set, but I still get  "Jhove ErrorMessage: Value offset not word-aligned: 1959335".
and Die Jhove-Validierung wurde nicht bestanden ( Status: Not well-formed).
As I know with the config setting: byteoffset=true, we should get only warning and file should be valid, if it has only this word alignment problem. 

I tried to upload the image, but TIFF is not allowd, so changed the extension to png.
If I can send you any additional info, please let me know.

Thanks.
![image_tif_rd](https://cloud.githubusercontent.com/assets/12269463/7489899/d88803b8-f3db-11e4-8c5e-cb8d2e9a3c3b.png)

**Comment by Chlara** [comment]
@zsole 

the TIFF spec says:
Rows must begin on byte boundaries.
(SHORT boundaries if the data is stored as
SHORTs, LONG boundaries if the data is stored as LONGs).
Some graphics systems require image data rows to be word-aligned or double-word-
aligned, and padded to word-boundaries or double-word boundaries. Uncompressed
TIFF rows will need to be copied into word-aligned or double-word-aligned row
buffers before being passed to the graphics routines in these environments

In KOST-Val this will always been validated, but I saw that I forgot to delete the line "<param>byteoffset=true</param>" in jhove.conf. In fact jhove.conf is set in Module KOST-Val\src\main\java\ch\kostceco\tools\kostval\validation\moduletiff2\impl\ValidationBjhoveValidationModuleImpl.java

Thanks.
Chlara

**Comment by zsole** [comment]
Hi,

Thanks for your quick reply. Really appreciate that.

In my opinion, according to TIFF spec, the tag values to be on byte boundary is only EXPECTED, but not MUST, if this does make sense. Check here:  https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf (Page 15, beginning at this page).

Do you think that this means that an uneven byteoffset is also acceptable?

BUT my main problem is that KOST-val seems to skip this "byteoffset=true", and reports as an error not a warning. Do you know why?

Thanks.

**Comment by Chlara** [comment]
hi @zsole 

No it's not expected if it is uncompressed: See page 30 (Chapter Compression; 1 = No compression; the last clause): Rows must begin on byte boundaries.

The fact, that the rows don't begin on byte boundaries makes that Jhove can't read all the tags and KOST-Val can't validate for example the color space. 

For us your TIFF is not acceptable. I'm sorry. 

Chlara
