### ISSUE TITLE
Weiter Formate zur Validierung

### ISSUE THREAD

**Issue by Chlara** [KOST-CECO/KOST-Val#34]
**Audio:**
- MP3 _(MP3val)_
- WAVE _(Jhove 1.14)_

**Hypertext:**
- WARC _(Jhove 1.14)_

**Video:**
- MP4
- MJ2

**Comment by tomcbe** [comment]
Hallo @Chlara 

Gibt es eine Möglichkeit, die Datei-Formatvalidierung in KOST-Val zu deaktivieren bzw. sämtliche Dateiformate zuzulassen? Wir möchten bei docuteam KOST-Val verwenden, um den Aufbau von SIPs zu prüfen, da die Dateien aber zu einem späteren Zeitpunkt migriert werden, sollen beliebige Dateiformate zugelassen werden.

Beste Grüsse
Thomas Bernhart

**Comment by Chlara** [comment]
In KOST-Val 2.x möglich (nur SIP)
