### ISSUE TITLE
Summary-Funktion im XML / XSLT

### ISSUE THREAD

**Issue by friesey** [KOST-CECO/KOST-Val#37]
Liebe Claire,
heute habe ich Kost-Val genutzt, um einen Ordner mit fast 600 PDF/A-Dateien zu validieren. Das hat auch super geklappt & die Performance war auch sehr gut. 
Was ich mir noch wünschen würde, zur besseren Auswertung würde ich als Nutzerin es sehr praktisch finden, wenn das Ausgabe-XML auch irgendwo oben oder unten sagen würde, wie viele PDF/A-Dateien aus dem Sample ingesamt valide bzw. invalide waren, damit ich Ergebnisse verschiedener PDF/A-Validatoren rascher miteinander vergleichen kann. 
Bei diesen Mengen mag ich nicht mehr selber zählen.
Viele Grüßli, Yvonne

**Comment by Chlara** [comment]
25545d3662329ea651dfeadeeaa3eba2f90716c1
