### ISSUE TITLE
DROID

### ISSUE THREAD

**Issue by DavidUnderdown** [KOST-CECO/KOST-Val#44]
Hi, while starting to research SIARD I noticed that you still seem to be using DROID 5 from sourceforge.  I just wanted to make sure you're aware that development has moved to GitHub https://github.com/digital-preservation/droid with releases on Maven Central, the current release is 6.2.1.  It may also be worth noting that there have been some quite big changes to the MP4 signatures (amongst others) in recent PRONOM updates.  We're expecting to release 6.3 fairly soon (probably by the end of the year, but not confirmed yet) and that will have some internal changes to file processing to address some issues that have come up in format identification with particular types of signature

**Comment by Chlara** [comment]
Hi david
Yes I use still DROID 5.0.3 because it was the version where I can easy get the PUID and DROID 5.0.3 works fine with other PRONOM versions.
In fact I use an own Signaturefile (https://github.com/KOST-CECO/KaD_SignatureFile) with the old DROID version. The KaD_SignatureFile is based on the  Pronom Version 72 and allows to identify what I need and that very fast.
Chlara

**Comment by DavidUnderdown** [comment]
Yes, I thought that was what you were doing.  As I say (though the signature files themselves should always be backwards compatible with previous DROID versions), there have been some quite big changes to signatures for particular formats in recent signature files, so you could potentially be missing things.  You should be able to get the same info in later versions of DROID, and again their are some known issues with some types of signature in the older versions now, but if it's not obvious how to get it do raise an issue in the GitHub repository, or ask on the mailing list.

**Comment by Chlara** [comment]
DROID was integrated directly into KOST-Tools. KOST-Val does not use DROID anymore.
