### ISSUE TITLE
PDF/A-Validierung

### ISSUE THREAD

**Issue by Chlara** [KOST-CECO/KOST-Val#45]
Ersetzten PDFTron mit veraPDF (sobald veraPDF besser ist als PDFTron)
duale validierung fix eingestellt (hat sich bewährt)
Hauptvalidator ist PDF Tools (bessere genauigkeit und geschwindigkeit)

**Comment by Chlara** [comment]
veraPDF hat nicht die gewünschte Qualität. Anstelle PDFTron soll wenn möglich callas verwendet werden.

**Comment by retokromer** [comment]
Ist callas nicht kommerziell?

**Comment by Chlara** [comment]
doch eigentlich schon, aber das ist ja PDF Tools auch... Wir sind am verhandeln, dass wir die Validierung kostenlos bekommen.

**Comment by akuckartz** [comment]
Was ist an veraPDF nicht ausreichend gut?

**Comment by Chlara** [comment]
@akuckartz 
In unserer Studie (https://kost-ceco.ch/cms/index.php?pdfa_validatoren_de) bemängeln wir diverse Sachen an veraPDF. Nebst der Qualität auch die Mangelhafte Robustheit und Geschwindigkeit.

**Comment by Chlara** [comment]
erledigt: 79c9ec847c3438af6df0f36b846a752e6423865a
