### ISSUE TITLE
TIFF-FileSize in Standardkonfiguration nicht zulässig obwohl <1000 MB

### ISSUE THREAD

**Issue by wadoli** [KOST-CECO/KOST-Val#49]
Guten Tag

KOST-Val v1.9.3 meldet ausgeführt auf Windows 10 bei einer TIFF-Datei den folgenden Fehler:

    Invalid:
    Validierung: TIFF -> U29050_14101968.tif
    H) Groesse | FileSize: 40360609 ist nicht zulaessig.`

Woher rührt dieser Fehler? Gemäss Handbuch S. 15 prüft für TIFF-Dateien der Validierungsschritt H «Grösse» die Frage, ob die Dateigrösse von der Konfiguration erlaubt ist. In der Standardkonfiguration ist für `<allowedsize>0</allowedsize>` eingestellt und Dateien dürfen entsprechend nicht grösser als 1000 MB gross sein. Die fragliche Datei ist aber nur 49.3 MB gross.

Der Fehler trat bei mehreren getesteten TIFFs auf, die aber alle nur rund 50 MB gross sind.

Ich wäre froh um einen Hinweis auf die Ursache für den Fehler.

Unten habe ich der Vollständigkeit halber noch die Prüfresultate der Datei mit den aktuellen Versionen von ExifTool und Jhove eingefügt. In diesem Zusammenhang: Gibt es einen besonderen Grund, dass in KOST-Val 1.9.3 vom 21.01.2019 die Version 1.5 von Jhove von Ende 2009 zum Einsatz kommt?

Freundliche Grüsse,
  Oliver Waddell

Exiftool 11.31 hat mit den Metadaten der Datei nur «minor»-Probleme:

    exiftool -validate -warning -error -a U29050_14101968.tif
    Validate                        : 2 Warnings (all minor)
    Warning                         : [minor] Invalid date/time format for XMP:DateTimeOriginal
    Warning                         : [minor] Oversized IFD0 StripByteCounts (51762816 bytes, but expected 51664032)

Jhove 1.20.1 mit der Standardkonfiguration meint die Datei sei «Well-Formed and valid»:

    jhove.bat U29050_14101968.tif
    Jhove (Rel. 1.20.1, 2018-03-29)
     Date: 2019-03-12 14:53:53 MEZ
     RepresentationInformation: U29050_14101968.tif
      ReportingModule: TIFF-hul, Rel. 1.8 (2017-05-11)
      LastModified: 2019-03-11 11:45:41 MEZ
      Size: 51770318
      Format: TIFF
      Version: 5.0
      Status: Well-Formed and valid
      SignatureMatches:
       TIFF-hul
      MIMEtype: image/tiff
      Profile: Baseline RGB (Class R), DLF Benchmark for Faithful Digital Reproductions of Monographs and Serials: color
      TIFFMetadata:
       […]

**Comment by Chlara** [comment]
Guten Tag Herr Waddell

Herzlichen Dank für Ihren Issue. Leider habe ich bis jetzt keine solche Datei gefunden. Wäre es möglich, dass Sie mir eine zukommen lassen (kost-val@kost-ceco.ch), damit ich es beheben kann?Ich vermute, dass es was mit der Einheit zu tun hat, möchte aber sicher sein.

Claire Röthlisberger

**Comment by wadoli** [comment]
Guten Tag Frau Röthlisberger

Danke für die Rückmeldung! Ich habe Ihnen eben drei Dateien, bei welchen KOST-Val den Fehler im Validierungsschritt H zurückmeldet, über die WebTransfer ZH-Plattform an die angegebene Adresse geschickt.

Freundliche Grüsse
  Oliver Waddell

**Comment by Chlara** [comment]
Besten Dank für die Bilder.

Der Fehler ist nicht durch die Einheit verschuldet sondern von den xmp Metadaten:

<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9-9, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='Exif XMP schema' xmlns:exif='http://ns.adobe.com/exif/1.0/' exif:ColorSpace='1' exif:PixelXDimension='6353' exif:PixelYDimension='6252' exif:DateTimeOriginal='1804101356'/>
<rdf:Description rdf:about='Exif XMP schema' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Keywords=''/>
<rdf:Description rdf:about='Exif XMP schema' xmlns:tiff='http://ns.adobe.com/tiff/1.0/' tiff:Make='Creo' tiff:Model='iQSmart	2' tiff:MediaType='Negative' tiff:OriginalType='Transparent' tiff:ScanQuality='Standard' tiff:CropSizeH='58.3454132080078' tiff:CropSizeW='57.4166870117188' tiff:Resolution='71.7259826660156' tiff:ScaleFactor='151.820007324219' tiff:Format='image/tiff' **tiff:FileSize='40360609'** tiff:Compression='1' tiff:Software='oXYgen Scan, Ver 2.6.3' tiff:AnalogLightFactor='1' tiff:Depth='8'/>
</rdf:RDF>
</x:xmpmeta>

Ich habe jetzt eine Möglichkeit gefunden anzuzeigen, von wo die Angaben herkommen, damit ich es herausfiltern kann:
[File:System] FileName: 02-Original.tif
[File:System] Directory: H:/data/Documents/Haengeregister_Dektop/ToDo/TIFF_H_Groesse
[EXIF:IFD0] Compression: Uncompressed
[XMP:XMP-tiff] Compression: Uncompressed
[EXIF:IFD0] PhotometricInterpretation: RGB
[EXIF:IFD0] PlanarConfiguration: Chunky
[EXIF:IFD0] BitsPerSample: 8 8 8
[EXIF:IFD0] StripByteCounts: (Binary data 1833 bytes, use -b option to extract)
[EXIF:IFD0] RowsPerStrip: 16
[File:System] FileSize: 49 MB
**[XMP:XMP-tiff] FileSize: 40360609**

Die Umsetzung ist noch offen, wird aber in Angriff genommen.

**Comment by wadoli** [comment]
Sehr schön, danke für die rasche Rückmeldung!

**Comment by Chlara** [comment]
Erledigt :smiley:
Siehe Release 1.9.4: https://github.com/KOST-CECO/KOST-Val/releases/tag/v1.9.4
