### ISSUE TITLE
Weiss nicht wie man das Programm ausführt

### ISSUE THREAD

**Issue by DinoAGW** [KOST-CECO/KOST-Val#51]
Schönen guten Tag,
mir wurde KOST-Val empfohlen, aber trotz Anleitung und stundenlangem ausprobieren fehlt mir irgendwas um es am Laufen zu kriegen.
Ich habe versucht es als Java Projekt zu importieren und zu starten (weil da Java Dateien vorhanden sind), da sagt er aber da ist keine Main vorhanden (obwohl da eine ist).
Die Anleitung besagt die exe bzw die Konsole startet die kostval_de.jar, welche im Screenshot zwar zu sehen ist, aber in dem Ordner ist keine Jar, sondern der Ordnername besagt sogar notJar - aber wo kriege ich die jar Dateien dann her, oder wie mache ich sie?
Wäre um Hilfe dankbar.
Viele Grüße, Dino

**Comment by Chlara** [comment]
Hallo Dino

Das Projekt musst du nicht importieren, das ist viel zu kompliziert. Wie es im Readme steht einfach KOST-Val unter https://github.com/KOST-CECO/KOST-Val/releases herunterladen. Dort findest du auch das Handbuch mit der Installationsanleitung (= KOST-Val.zip entzippen). 
Chlara
