### ISSUE TITLE
[v2.0.0.beta2] FileNotFoundException

### ISSUE THREAD

**Issue by wilpert** [KOST-CECO/KOST-Val#53]
Beim Versuch, die Dateiformate unter einem Ordner mit KOST-Val v2.0.0.beta2 zu validieren, bekomme ich bei einer der Dateien die folgende Fehlermeldung:

Validierung: PDFA-2U -> DATEI.pdf

A) Allgemeines | Ein unbekannter Fehler ist aufgetreten. FileNotFoundException

KOST-Val v1.9.8 validiert erfolgreich die Datei. Die Datei habe ich sonst mit anderen Tools problemlos öffnen und validieren können (z. B. mit PDF Tools und DROID). Ein Problem mit der Pfadlänge kann ausgeschlossen werden (ich habe es bereits getestet).

Zur Info: Auf meinem Rechner ist JavaFX 8.0.191 und Java-32 1.8.0_191 installiert.

**Comment by Chlara** [comment]
Besten Dank für die Meldung @wilpert .

Ich hoffe ich konnte den Fehler mit der beta3 Version beheben: https://github.com/KOST-CECO/KOST-Val/releases/tag/v2.0.0.beta

Könntest du dies für mich kontrollieren? Herzlichen Dank!

**Comment by wilpert** [comment]
Herzlichen Dank @Chlara für die neue beta3 Version; ich habe es gerade überprüft und leider tritt derselbe Fehler weiterhin auf.

**Comment by Chlara** [comment]
Danke fürs Testen @wilpert 
Könntest du die ganze Fehlermeldung (FileNotFoundException) hereinkopieren, welche im unteren grauen (Konsolen-) Fenster erscheint. Dann ist es für mich einfacher besser herauszufinden, welche Datei bei dir nicht gefunden wird.
Besten Dank! Chlara

**Comment by wilpert** [comment]
Guten Morgen @Chlara,
ich habe die Dateiformate mit KOST-Val (v2.0.0.beta3) nochmals validieren lassen. Die ganze Fehlermeldung folgt:
![grafik](https://user-images.githubusercontent.com/7935490/96413576-24114e00-11ec-11eb-9493-a00252619bd0.png)
Die Validierung habe ich im Kontext einer Abnahme einer digitalen Ablieferung ans Staatsarchiv (AG) durchgeführt. Die Dokumente sind unter Schutzfrist und deshalb darf ich mit Dir das betroffene PDF-Dokument leider nicht teilen.
LG, Alexis

**Comment by wilpert** [comment]
@Chlara:
Ich habe die drei Testdateien validieren lassen, die Du mir geschickt hast: 5.2.1_Ausloeser.pdf, 5.2.5_U+FFFD.pdf, 5.2.6_missmatch.pdf. Beim ersten und dritten Dokument meldet KOST-Val (v2.0.0.beta3) ebenso _Ein unbekannter Fehler ist aufgetreten. FileNotFoundException_
Die vollständige Meldung im unteren grauen Fenster ist:

KOST-Val
2 PDFA:  C:\Users\AWZ1\Downloads\TEST\5.2.1_Ausloeser.pdf = Invalid
1 PDFA:  C:\Users\AWZ1\Downloads\TEST\5.2.5_U+FFFD.pdf = Invalid
0 PDFA:  C:\Users\AWZ1\Downloads\TEST\5.2.6_missmatch.pdf = Invalid
Formatvalidierung durchgefuehrt.                                                              
 -> Von den 3 Dateien sind 0 (0%) valid, 3 (100%) invalid und 0 (0%) wurden nicht validiert.  
 -> C:\Users\AWZ1\.kost-val_2x\logs\TEST.kost-val.log.xml

java.lang.NullPointerException
	at com.sun.webkit.MainThread.fwkScheduleDispatchFunctions(MainThread.java:34)

Die Java-Exception wird nicht immer angezeigt: Wenn ich KOST-Val neu starte und eine erste Validierung durchführe, wird die angezeigt; bei einem zweiten Lauf nicht mehr.

Zur Info, meine Konfiguration:

![grafik](https://user-images.githubusercontent.com/7935490/96556658-8e43f480-12b9-11eb-9b96-6874d479b5e5.png)

**Comment by Chlara** [comment]
@wilpert 

Jetzt wo wir gemeinsame Testdaten gefunden haben, welche das Problem auslösen, konnte ich bei mir den Bug beheben. 
Könntest du es bitte auch noch bei dir testen mit gamma1?

https://github.com/KOST-CECO/KOST-Val/releases/tag/2.0.0.gamma

Besten Dank!

Chlara

**Comment by wilpert** [comment]
Danke @Chlara 

KOST-Val v2.0.0.gamma1 stuft bei mir das Dokument weiterhin als "invalid" ein. Übrigens die anderen drei von Dir geteiten Test-Dokumente auch.

Die bereits erwähnte Java-Exception wird beim ersten Lauf auch bei dieser Version angezeigt:
_java.lang.NullPointerException
	at com.sun.webkit.MainThread.fwkScheduleDispatchFunctions(MainThread.java:34)_

Meine Java-Umgebung:
![grafik](https://user-images.githubusercontent.com/7935490/96711576-10a5e480-139e-11eb-831b-5fb1ab8df25d.png)

Meine Konfiguration:
![grafik](https://user-images.githubusercontent.com/7935490/96711627-25827800-139e-11eb-83c9-6948631cfcd7.png)

**Comment by Chlara** [comment]
Der Bug "A) Allgemeines | Ein unbekannter Fehler ist aufgetreten. FileNotFoundException" ist mit gamma1 behoben.

Die Meldung "java.lang.NullPointerException
at com.sun.webkit.MainThread.fwkScheduleDispatchFunctions(MainThread.java:34)" im Konsolenfenster ist scheinbar ein oracle-Bug und hat keinen Einfluss aufs Resultat. Evtl kann ich den später beheben / abfangen.

**Comment by wilpert** [comment]
@Chlara: Herzlichen Dank für die Behebung und vor allem für KOST-Val
