### ISSUE TITLE
Java Fehlermeldung

### ISSUE THREAD

**Issue by Theresa12** [KOST-CECO/KOST-Val#54]
Auf meinem neuen PC erhalte ich beim Validieren immer folgende Fehlermeldung:
"Allgemeiner Java Fehler beim Programmablauf: java.exe-jar kostval_de.jar --format"

Als Java Version läuft die Version 8 Update 192 (Build 1.8.0_192-b12).

Weiß jemand wie man das beheben kann?
Danke schonmal :)

**Comment by Chlara** [comment]
Ich weiss nicht ob es ein Copy Paste Fehler ist oder nicht aber zwischen **java.exe** und **-jar** muss ein **Leerschlag** sein. 

Allgemein wäre es auch hilfreich die Version von KOST-Val zu wissen.

**Comment by Chlara** [comment]
Im Handbuch Kapitel 8.2 sind die einzelnen Bestandteile beschrieben: 

Anhand kostval_de.jar ist es eine Version 1.x von KOST-Val. Da besteht der Programmaufruf aus 4-5 Bestandteile (im Handbuch A-E genannt). 

Hier ein kleines Beispiel: 
**java -jar kostval_de.jar --format O:\AMT\Dateisammlung -v** 

Nach --format muss der Pfad zur Datei oder dem Ordner erfolgen. -v (Verbose-Option) wird meistens weggelassen.
