### ISSUE TITLE
There is no ID/IDREF binding for IDREF 'd000680'. (Mss)

### ISSUE THREAD

**Issue by CarlitosHa** [KOST-CECO/KOST-Val#55]
Liebe KOST

Ich habe ein SIP vorliegen, das ich zweimal validiert habe. Beim ersten Mal gab es nur einige Pfade, die zu lang waren. Nachdem ich die erlaubte Pfadlänge erhöht habe, gab es dann nur noch eine Fehlermeldung, die allerdings davor gar nicht gekommen war und zwar:

`metadata.xml, Zeile 72'370 --> Fehlermeldung: cvc-id.1: There is no ID/IDREF binding for IDREF 'd000680'. (Mss) -> Validierung abgebrochen!`

Zeile 72'370 ist die letzte Zeile von metadata.xml und das <dateiRef> mit dem genannten Wert kommt aber irgendwo mittendrin.

Die Nachricht "Validierung abgebrochen" lässt mich vermuten, dass die Validierung eigentlich noch weitergehen müsste. Stimmt das?

Wie so oft können wir das originale SIP vermutlich nicht teilen. Aber vielleicht könnt ihr mir einen Ratschlag geben, was ich allenfalls anders machen könnte?

Beste Grüsse
Carlos Hartmann

**Comment by Chlara** [comment]
Bilateral erledigt
