### ISSUE TITLE
Validierungsprotokoll kann nicht gespeichert oder als PDF gedruckt werden

### ISSUE THREAD

**Issue by CarlosHartmann** [KOST-CECO/KOST-Val#56]
Ich habe bei der neuesten Version ein Problem beim Abspeichern der Validierungsprotokolle. Der Button "speichern" löst nichts aus, wird dann irgendwo in der Installations-directory ein XML abgelegt?

Statt "speichern" habe ich bisher "drucken" verwendet und Microsoft Print to PDF, aber der Output sind 0KB-grosse PDFs. Ist das ein bekannter Bug?

**Comment by Chlara** [comment]
Hallo Carlos

Kannst du bitte mal die Version 2.0.4 ausprobieren? Das Printing-Problem sollte jetzt behoben sein.
Anbei noch ein kleiner Hinweis: Beim Speichern kann nur ein Ordner ausgewählt werden. Denn es werden jeweils zwei Dateien gespeichert (XML und das dazugehörende XSL.
