### ISSUE TITLE
Aktuelle Version von Jhove einbinden in Kost-Val

### ISSUE THREAD

**Issue by adrianoettli** [KOST-CECO/KOST-Val#57]
Aktuell ist Jhove Version 1.5 eingebunden im Kost-Val 2.0.2. Diese Version von Jhove hat den Bug, dass der TIFF-Tag 700 fälschlicherweise als Fehler beanstandet werden kann. Dies wurde in V. 1.8 von Jhove korrigiert  [(https://sourceforge.net/p/jhove/bugs/38/)] da laut der XMP-Spezifikation von Adobe auch der Wert 7 (undefined) valide ist. 

Es wäre schön, wenn die neuste Version von Jhove eingebunden werden könnte.
Vielen Dank und herzliche Grüsse
Adrian Oettli
Staatsarchiv Thurgau

**Comment by Chlara** [comment]
Hallo Adrian

Besten Dank für den Hinweis. Wir haben noch nicht beschlossen ob wir ein update machen werden oder einen anderen Validator einsetzen. Es gibt noch andere Probleme mit Jhove die behoben werden müssen. Ich halte dich auf dem laufenden

**Comment by Chlara** [comment]
Kleines Update. Georg hat für uns den Issue gemeldet, welcher wir gerne behoben hätten in einer neuen Version

https://github.com/openpreserve/jhove/issues/678

**Comment by Chlara** [comment]
@adrianoettli 
Hallo Adrian 
Kannst du eine TIFF mit dem 700er Tag zur Verfügung stellen oder mir mailen?
Ich habe in meinem Fundus noch keine gefunden.

Merci.  Liebi Grüessli      Claire

**Comment by Chlara** [comment]
Lieber Adrian
Es müsste mit https://github.com/KOST-CECO/KOST-Val/releases/tag/v2.0.5  behoben sein. 
Liebi Güessli    Claire
