### ISSUE TITLE
Zusätzliche Formate als Fehler angemerkt, die in der Config erlaubt wurden

### ISSUE THREAD

**Issue by CarlosHartmann** [KOST-CECO/KOST-Val#59]
KOST-Val Version 2.0.4

In der Konfiguration habe ich ISO und CUE unter der Einstellung PUID hinterlegt, also wo die erlaubten Formate stehen.

Bei der Validierung wird folgendes zurückgemeldet:

3A) Formaterkennung | fmt/468 = 5 Datei(en)
-- | --

und pro Datei das hier:

3B) Zusaetzliche Formate | content/Datenobjekte/Aids-Plakate International, Bildsammlung 1985-1997, Aids Info Docu Schweiz/CD.iso (fmt/468 Extension: iso)
-- | --

An sich hätte ich erwartet, dass keine Fehlermeldung kommen sollte. Ausserdem vermute ich, dass weitere Prüfungsschritte (3C, 3D, ...) eventuell nicht mehr gemacht werden dadurch (?)

Das betroffene SIP untersteht keiner Schutzfrist, ich könnte die Daten also zur Verfügung stellen, falls nötig.

**Comment by Chlara** [comment]
Hallo Carlos

Kannst du mir das SIP mailen? ich muss überprüfen ob meine KaD-Signaturefile diese Dateien korrekt erkennt.

Ich nehme an, dass ich eine neue Version der KaD-Signaturefile erstellen muss und dir dann sagen kann, was du in die Konfig hereinschreiben kannst.

**Comment by CarlosHartmann** [comment]
Danke nochmals fürs Feedback. Man kann Formate also erlauben, indem man fmt/468 etc. in der Konfiguration angibt.
