### ISSUE TITLE
Konvertierung fehlgeschlagen. Ursache: KOST-VAL Validierung fehlgeschlagen. 

### ISSUE THREAD

**Issue by EdiCortesi** [KOST-CECO/KOST-Val#61]
Wir haben Adobe InDesign 15.1 und Acrobat Reader im Einsatz und nutzen den open eGOV Local Signer. 

Die Fehlermeldung erscheint nicht bei allen Benutzern, sondern nur bei denjenigen die obige Konstellation haben. 

Die Fehlermeldung lautet: Konvertierung fehlgeschlagen. Ursache: KOST-VAL Validierung fehlgeschlagen. 

Danke für Tipps. 
Edi

**Comment by Chlara** [comment]
Hallo Edi

Sorry, du wendest dich an die falsche Entwicklerin. KOST-Val validiert PDF/A-Dokumente und bemängelt Probleme in Dateien. In deinem Fall ist KOST-Val nur die Kontrollinstanz bei einem vorgelagerten Konvertierungsprozess, welcher nicht von uns stammt.

Für Implementierungsprobleme innerhalb fremd Software sind wir nicht zuständig. Wende dich an den Hersteller des Konvertierungstools!

Schau doch mit den anderen Entwicklern (z.B. ActaNova), dass sie die Fehlermeldung von KOST-Val nicht unterdrücken. Dann wüsstest du, warum die Validierung fehlschlägt.  

Claire, KOST

**Comment by EdiCortesi** [comment]
Hallo Claire

Danke für den Hinweis.

Gruss Edi


Von meinem iPhone gesendet

Am 29.06.2021 um 10:54 schrieb Claire Röthlisberger ***@***.***>:

﻿

Closed #61<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKOST-CECO%2FKOST-Val%2Fissues%2F61&data=04%7C01%7C%7Cdea01e91ae3c4c32ee2808d93adb9146%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637605536984404474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SwAggmYfC4D1kX7JHmciTiKAhcN1Z6BqUmYDkqQoRqY%3D&reserved=0>.
