### ISSUE TITLE
where is the log-file?

### ISSUE THREAD

**Issue by ralfhauser** [KOST-CECO/KOST-Val#65]
back on windows10

C:\Program Files\Amazon Corretto\jdk11.0.8_10\bin>.\java.exe -jar cmd_KOST-Val.jar --format DOC_t4141.pdfa --de --max
KOST-Val
C:\Program Files\Amazon Corretto\jdk11.0.8_10\bin\DOC_t4141.pdfa  = Invalid

but there is no log file in the directory

**Comment by Chlara** [comment]
KOST-Tools.msi (https://github.com/KOST-CECO/KOST-Val/releases/tag/KOST-Tools_v1.0.3) is used to install KOST-Val together with other archive tools and the appropriate Java.

Accordingly, such errors should be fixed indirectly.
