### ISSUE TITLE
Validierung von nicht konfigurierten bzw. nicht erkannten Dateitypen

### ISSUE THREAD

**Issue by oschihin** [KOST-CECO/KOST-Val#91]
# Problem

Bei der Dateivalidierung (mehrere Tausend Dateien in einem Ordner) erhalten wir neben den korrekten Validierungsresultaten auch einige Resultate aus Schritt A) "Die Datei wird nicht akzeptiert". Es handelt sich konkret um Dateien mit Endung `*.odt` und `*.eml`. Ich kann diese Dateitypen nicht zur Liste der akzeptierten Dateiformate hinzufügen, soweit ich sehe, auch nicht in der hinterlegten Konfigurationsdatei (`kostval.conf.xml`)

# Vorschlag

Die Liste der akzeptierten Dateiformate soll eine weitere Option für die freie Eingabe von Endungen erhalten.

**Comment by Chlara** [comment]
EML und Feld für weitere Eingabe hinzugefügt.

![Screenshot 2024-07-16 101600](https://github.com/user-attachments/assets/c7a5aa92-3671-4017-8d35-68720f89b9fb)

**Comment by Chlara** [comment]
557e686
